### ISSUE TITLE
Ensure compatibility with Windows

### ISSUE THREAD

**Issue by chughts** [ibm-messaging/mq-dev-badge-sample#14]
Ensure the sample runs on Windows as well as Linux and MacOS.

**Comment by chughts** [comment]
Something for you @Tanmay-Kudchadkar ?

**Comment by dernoun** [comment]
@chughts The docker file contain only commands for Linux system, I was not able to run it on windows, might I miss something ?

**Comment by chughts** [comment]
@dernoun The docker container is Linux / X86, but this should run on Docker on Windows / X86. 

The windows issue is due to the use of symbolic links to the source files, which were introduced to reuse code without having to make duplicate copies. Windows doesn't handle the symbolic links well. 

As the docker file is now making use of maven to build the application, I think the code should just be moved to where maven is expecting to find it, and removed from its original directory structure. I think this is the task for @Tanmay-Kudchadkar

**Comment by chughts** [comment]
This should be fixed in #20

**Comment by haegray** [comment]
Hello,

I tried running the code on Docker and it initially runs but then crashes saying it cannot find or load the main class. I'm working on Windows 10

**Comment by chughts** [comment]
It looks like the windows symbolic link fix isn't working. I will double check that there isn't any documentation that refers to the old location, and permanently move the code instead.

**Comment by chughts** [comment]
Fixed in #22
